  AWSTemplateFormatVersion: '2010-09-09'
  Transform: AWS::Serverless-2016-10-31
  Description: AWS Serverless Quarkus HTTP - quarkus-lambda-course-rest-1.0.0-SNAPSHOT
  Globals:
    Api:
      EndpointConfiguration: REGIONAL
      BinaryMediaTypes:
        - "*/*"

  Resources:
    QuarkusLambdaCourseRest:
      Type: AWS::Serverless::Function
      Properties:
        Handler: io.quarkus.amazon.lambda.runtime.QuarkusStreamHandler::handleRequest
        Runtime: java17
        CodeUri: target/function.zip
        MemorySize: 2048
        Policies:
          - AWSLambdaBasicExecutionRole
          - DynamoDBCrudPolicy:
              TableName: !Ref CourseDDBTable
          - DynamoDBCrudPolicy:
              TableName: !Ref LessonDDBTable

        Timeout: 150

    CourseDDBTable:
      Type: AWS::Serverless::SimpleTable
      Properties:
        TableName: Course
        PrimaryKey:
          Name: id
          Type: Number
    LessonDDBTable:
      Type: AWS::Serverless::SimpleTable
      Properties:
        TableName: Lesson
        PrimaryKey:
          Name: id
          Type: Number
